### ISSUE TITLE
Access tokens are printed in results file

### ISSUE THREAD

**Issue by jperezdealgaba** [RedHatProductSecurity/rapidast#332]
At least with the Garak integration, if the user writes an access token inside the configuration file, that token is later showed in the results files as part of the garak configuration:

```
RestGenerator:
              headers:
                Authorization: Bearer <redacted>
                Content-Type: application/json
                Referer: XXXXX
```

In other section of the configuration files, such as the `general/authentication`, the token is obfuscated at the time of printing the results:

```
general:
  authentication:
    parameters:
      password: '*****'
      username: '*****'
    type: http_basic
```

I don't know if that's an expected behavior, but I can imagine that for users with public pipelines and artifacts, they don't want their token to be published as part of the results files. The tokens inside Garak should also be obfuscated in order to enhance the security of our pipelines.
