### ISSUE TITLE
Exclude urls from zap's apiScan

### ISSUE THREAD

**Issue by MrMarble** [RedHatProductSecurity/rapidast#377]
We are having issues with one endpoint in our application as it is used for report generation, it takes a couple of minutes to load all the data and thus Zap fails with a `ZapSocketTimeoutException: Read timed out`.
I've read through the documentation and the configmodel for zap and I don't see a way of increasing the timeout, so I thought about excluding that endpoint from the scan but I failed to do so.

Is the `urls.excludes` not taken into account when using a `apiScan`? I have tried multiple forms of regex, even the full url as is, but the error persist, here's the configuration (actual url is redacted):

```yaml
config:
  configVersion: 5

application:
  shortName: "osidb-stage"
  url: "https://redacted.redhat.com"

scanners:
  zap:
    apiScan:
      apis:
        apiUrl: "https://redacted.redhat.com/osidb/api/v1/schema"

    passiveScan:
      # optional list of passive rules to disable
      disabledRules: "2,10015,10024,10027,10054,10096,10109,10112"

    activeScan:
      policy: "API-scan-minimal"

    urls:
      excludes:
        - ^https?:\/\/redacted\.redhat\.com\/osidb\/api\/v1\/audit.*$
        - https://redacted.redhat.com/osidb/api/v1/audit/pgh_slug
        - "^https?://redacted.redhat.com/osidb/api/v1/audit/.*$"
   ```

**Comment by MrMarble** [comment]
> (I haven’t personally tested this exact setting, please let me if it works)

That seems to work, thanks!
> However, keep in mind that ZAP might still contact those URLs in some cases, for example, when importing OpenAPI specs

Would this [Global Exclusions](https://www.zaproxy.org/docs/desktop/addons/network/options/globalexclusions/) allow to exclude urls from being reached?

**Comment by MrMarble** [comment]
I had to remove the escaping on the parenthesis because Zap was complaining, but even with that it did not seem to work, this was my config:
```yaml
    miscOptions:
      overrideConfigs: 
        - network.connection.timeoutInSecs=240
        - network.globalExclusions.exclusions.exclusion(0).name=redhat
        - network.globalExclusions.exclusions.exclusion(0).value=^.*\.redhat\.com.*$
        - network.globalExclusions.exclusions.exclusion(0).enabled=true
```

The only one that seems to work is the `timeoutInSecs`, the openApi job seems to ignore the other rules.
I'll close the issue as completed since the timeout seems to be enough, thanks!

If you want me to do further testing, please reopen the issue and I'll gladly help
